name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and Push the Docker image
      run: |
        image_timestamp=$(date +%s)
        echo "${{ secrets.DOCKERHUBPASSWORD}}" | docker login -u "iredkin" --password-stdin
        docker build . --file Dockerfile --tag iredkin/pro690image:$image_timestamp
        docker push iredkin/pro690image:$image_timestamp

    - name: Update Image Version in the related manifest.yaml
      uses: fjogeleit/yaml-update-action@main
      with:
        valueFile: 'argocd-openshift/memory-game/application-manifest/deployment.yaml'
        propertyPath: 'spec.template.spec.containers[0].image'
        value: iredkin/pro690image:$image_timestamp
        branch: main
        commitChange: true
        message: 'testing yaml change'
